using System;
using System.ComponentModel;

namespace System.Text.RegularExpressions
{
	/// <summary>The <see cref="T:System.Text.RegularExpressions.RegexRunner" /> class is the base class for compiled regular expressions.</summary>
	// Token: 0x0200048D RID: 1165
	[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
	[MonoTODO("RegexRunner is not supported by Mono.")]
	public abstract class RegexRunner
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Text.RegularExpressions.RegexRunner" /> class. </summary>
		// Token: 0x060029DE RID: 10718 RVA: 0x0008BC54 File Offset: 0x00089E54
		[MonoTODO]
		protected internal RegexRunner()
		{
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029DF RID: 10719
		protected abstract bool FindFirstChar();

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E0 RID: 10720
		protected abstract void Go();

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E1 RID: 10721
		protected abstract void InitTrackCount();

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E2 RID: 10722 RVA: 0x0008BC5C File Offset: 0x00089E5C
		[MonoTODO]
		protected void Capture(int capnum, int start, int end)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. Determines whether a character is in a character class.</summary>
		/// <returns>true if the <paramref name="ch" /> parameter is in the character class specified by the <paramref name="charClass" /> parameter.</returns>
		/// <param name="ch">A character to test.</param>
		/// <param name="charClass">The internal name of a character class.</param>
		// Token: 0x060029E3 RID: 10723 RVA: 0x0008BC64 File Offset: 0x00089E64
		[MonoTODO]
		protected static bool CharInClass(char ch, string charClass)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E4 RID: 10724 RVA: 0x0008BC6C File Offset: 0x00089E6C
		[MonoTODO]
		protected static bool CharInSet(char ch, string set, string category)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E5 RID: 10725 RVA: 0x0008BC74 File Offset: 0x00089E74
		[MonoTODO]
		protected void Crawl(int i)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E6 RID: 10726 RVA: 0x0008BC7C File Offset: 0x00089E7C
		[MonoTODO]
		protected int Crawlpos()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E7 RID: 10727 RVA: 0x0008BC84 File Offset: 0x00089E84
		[MonoTODO]
		protected void DoubleCrawl()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E8 RID: 10728 RVA: 0x0008BC8C File Offset: 0x00089E8C
		[MonoTODO]
		protected void DoubleStack()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029E9 RID: 10729 RVA: 0x0008BC94 File Offset: 0x00089E94
		[MonoTODO]
		protected void DoubleTrack()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029EA RID: 10730 RVA: 0x0008BC9C File Offset: 0x00089E9C
		[MonoTODO]
		protected void EnsureStorage()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029EB RID: 10731 RVA: 0x0008BCA4 File Offset: 0x00089EA4
		[MonoTODO]
		protected bool IsBoundary(int index, int startpos, int endpos)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029EC RID: 10732 RVA: 0x0008BCAC File Offset: 0x00089EAC
		[MonoTODO]
		protected bool IsECMABoundary(int index, int startpos, int endpos)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029ED RID: 10733 RVA: 0x0008BCB4 File Offset: 0x00089EB4
		[MonoTODO]
		protected bool IsMatched(int cap)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029EE RID: 10734 RVA: 0x0008BCBC File Offset: 0x00089EBC
		[MonoTODO]
		protected int MatchIndex(int cap)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029EF RID: 10735 RVA: 0x0008BCC4 File Offset: 0x00089EC4
		[MonoTODO]
		protected int MatchLength(int cap)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029F0 RID: 10736 RVA: 0x0008BCCC File Offset: 0x00089ECC
		[MonoTODO]
		protected int Popcrawl()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029F1 RID: 10737 RVA: 0x0008BCD4 File Offset: 0x00089ED4
		[MonoTODO]
		protected void TransferCapture(int capnum, int uncapnum, int start, int end)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method.</summary>
		// Token: 0x060029F2 RID: 10738 RVA: 0x0008BCDC File Offset: 0x00089EDC
		[MonoTODO]
		protected void Uncapture()
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x060029F3 RID: 10739 RVA: 0x0008BCE4 File Offset: 0x00089EE4
		protected internal Match Scan(Regex regex, string text, int textbeg, int textend, int textstart, int prevlen, bool quick)
		{
			throw new NotImplementedException();
		}

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A2A RID: 6698
		[MonoTODO]
		protected internal int[] runcrawl;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A2B RID: 6699
		[MonoTODO]
		protected internal int runcrawlpos;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A2C RID: 6700
		[MonoTODO]
		protected internal Match runmatch;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A2D RID: 6701
		[MonoTODO]
		protected internal Regex runregex;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A2E RID: 6702
		[MonoTODO]
		protected internal int[] runstack;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A2F RID: 6703
		[MonoTODO]
		protected internal int runstackpos;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A30 RID: 6704
		[MonoTODO]
		protected internal string runtext;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A31 RID: 6705
		[MonoTODO]
		protected internal int runtextbeg;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A32 RID: 6706
		[MonoTODO]
		protected internal int runtextend;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A33 RID: 6707
		[MonoTODO]
		protected internal int runtextpos;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A34 RID: 6708
		[MonoTODO]
		protected internal int runtextstart;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A35 RID: 6709
		[MonoTODO]
		protected internal int[] runtrack;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A36 RID: 6710
		[MonoTODO]
		protected internal int runtrackcount;

		/// <summary>Used by a <see cref="T:System.Text.RegularExpressions.Regex" /> object generated by the <see cref="Overload:System.Text.RegularExpressions.Regex.CompileToAssembly" /> method. </summary>
		// Token: 0x04001A37 RID: 6711
		[MonoTODO]
		protected internal int runtrackpos;
	}
}
