using System;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.ServicesGameServer.#NativeResultCallbacks(System.Int32,System.IntPtr,System.Int32,System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "ManagedSteam.Constants+Friends")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "ElseWhere", Scope = "member", Target = "ManagedSteam.SteamTypes.DenyReason.#LoggedInElseWhere")]
[assembly: SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "ManagedSteam.Utility")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.Steam.#NativeCallbacks(System.Int32,System.IntPtr,System.Int32)", Justification = "Must catch all exceptions as the code is called by native code")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.Steam.#NativeResultCallbacks(System.Int32,System.IntPtr,System.Int32,System.Boolean)", Justification = "Must catch all exceptions as the code is called by native code")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "ManagedSteam.Constants+Cloud")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "ManagedSteam.Constants+Stats")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudDeletePublishedFileResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudDownloadUGCResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudEnumeratePublishedFilesByUserActionResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudEnumerateUserPublishedFilesResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudEnumerateUserSharedWorkshopFilesResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudEnumerateUserSubscribedFilesResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudEnumerateWorkshopFilesResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudFileShareResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudGetPublishedFileDetailsResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudGetPublishedItemVoteDetailsResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudPublishFileResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudSetUserPublishedFileActionResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudSubscribePublishedFileResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudUnsubscribePublishedFileResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudUpdatePublishedFileResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudUpdateUserPublishedItemVoteResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudUserVoteDetails")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "WebPage", Scope = "member", Target = "ManagedSteam.IFriends.#ActivateGameOverlayToWebPage(System.String)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#GameOverlayActivated")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IStats.#GlobalAchievementPercentagesReady")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IStats.#GlobalStatsReceived")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IStats.#LeaderboardFindResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IStats.#LeaderboardScoresDownloaded")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IStats.#LeaderboardScoreUploaded")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IStats.#LeaderboardUGCSet")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IStats.#NumberOfCurrentPlayers")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IStats.#UserAchievementIconFetched")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IStats.#UserAchievementStored")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IStats.#UserStatsReceived")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IStats.#UserStatsStored")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IStats.#UserStatsUnloaded")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "e", Scope = "type", Target = "ManagedSteam.Steam+ExceptionDelegate")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.Steam.#ExceptionThrown")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "ManagedSteam.Steam+ExceptionDelegate")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "ManagedSteam.Steam+ExceptionDelegate")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Exceptions.NativeException.#.ctor(ManagedSteam.StringID,System.Object[])")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Exceptions.ManagedException.#.ctor(ManagedSteam.StringID,System.Object[])")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Exceptions.InvalidInterfaceVersionException.#.ctor(ManagedSteam.StringID,System.Object[])")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Exceptions.CallbackStructSizeMismatchException.#.ctor(ManagedSteam.StringID,System.Object[])")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Exceptions.AlreadyLoadedException.#.ctor(ManagedSteam.StringID,System.Object[])")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Exceptions.SteamInitializeFailedException.#.ctor(ManagedSteam.StringID,System.Object[])")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Exceptions.SteamInterfaceInitializeFailedException.#.ctor(ManagedSteam.StringID,System.Object[])")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Exceptions.UnexpectedException.#.ctor(ManagedSteam.StringID,System.Object[])")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Exceptions.UsageAfterAPIShutdownException.#.ctor(ManagedSteam.StringID,System.Object[])")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "ManagedSteam.Implementations.Cloud.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope = "type", Target = "ManagedSteam.SteamTypes.RemoteStoragePlatform")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1700:DoNotNameEnumValuesReserved", Scope = "member", Target = "ManagedSteam.SteamTypes.RemoteStoragePlatform.#Reserved1")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1700:DoNotNameEnumValuesReserved", Scope = "member", Target = "ManagedSteam.SteamTypes.RemoteStoragePlatform.#Reserved2")]
[assembly: SuppressMessage("Microsoft.Design", "CA1008:EnumsShouldHaveZeroValue", Scope = "type", Target = "ManagedSteam.SteamTypes.ResolveConflict")]
[assembly: SuppressMessage("Microsoft.Design", "CA1008:EnumsShouldHaveZeroValue", Scope = "type", Target = "ManagedSteam.SteamTypes.Result")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Logon", Scope = "member", Target = "ManagedSteam.SteamTypes.Result.#AccountLogonDenied")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Logon", Scope = "member", Target = "ManagedSteam.SteamTypes.Result.#AccountLogonDeniedNoMail")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Logon", Scope = "member", Target = "ManagedSteam.SteamTypes.Result.#AccountLogonDeniedVerifiedEmailRequired")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Cancelled", Scope = "member", Target = "ManagedSteam.SteamTypes.Result.#Cancelled")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "ManagedSteam.SteamTypes.Result.#ExpiredLoginAuthCode")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Facebook", Scope = "member", Target = "ManagedSteam.SteamTypes.Result.#FacebookQueryError")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "ManagedSteam.SteamTypes.Result.#InvalidLoginAuthCode")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Param", Scope = "member", Target = "ManagedSteam.SteamTypes.Result.#InvalidParam")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ver", Scope = "member", Target = "ManagedSteam.SteamTypes.Result.#InvalidProtocolVer")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Login", Scope = "member", Target = "ManagedSteam.SteamTypes.Result.#IPLoginRestrictionFailed")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "Logon", Scope = "member", Target = "ManagedSteam.SteamTypes.Result.#LogonSessionReplaced")]
[assembly: SuppressMessage("Microsoft.Design", "CA1008:EnumsShouldHaveZeroValue", Scope = "type", Target = "ManagedSteam.SteamTypes.ChatEntryType")]
[assembly: SuppressMessage("Microsoft.Design", "CA1008:EnumsShouldHaveZeroValue", Scope = "type", Target = "ManagedSteam.SteamTypes.ServerMode")]
[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "ManagedSteam.INetworking.#IsP2PPacketAvailable(System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "ManagedSteam.INetworking.#IsP2PPacketAvailable(System.UInt32&,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "ManagedSteam.INetworking.#ReadP2PPacket(System.Byte[],System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "ManagedSteam.INetworking.#ReadP2PPacket(System.Byte[],System.UInt32&,ManagedSteam.SteamTypes.SteamID&,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "ManagedSteam.INetworking.#SendP2PPacket(ManagedSteam.SteamTypes.SteamID,System.Byte[],ManagedSteam.SteamTypes.P2PSend,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.MatchmakingPingResponse.#ServerFailedToRespondCallback(System.UInt32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.MatchmakingPingResponse.#ServerRespondedCallback(System.UInt32,System.IntPtr,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.MatchmakingPlayersResponse.#AddPlayerToListCallback(System.UInt32,System.IntPtr,System.Int32,System.Single)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.MatchmakingPlayersResponse.#PlayersFailedToRespondCallback(System.UInt32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.MatchmakingPlayersResponse.#PlayersRefreshCompleteCallback(System.UInt32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.MatchmakingRulesResponse.#RulesFailedToRespondCallback(System.UInt32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.MatchmakingRulesResponse.#RulesRefreshCompleteCallback(System.UInt32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.MatchmakingRulesResponse.#RulesRespondedCallback(System.UInt32,System.IntPtr,System.IntPtr)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.MatchmakingServerListResponse.#RefreshCompleteCallback(System.UInt32,System.UInt32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.MatchmakingServerListResponse.#ServerFailedToRespondCallback(System.UInt32,System.UInt32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.MatchmakingServerListResponse.#ServerRespondedCallback(System.UInt32,System.UInt32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "ManagedSteam.ServicesGameServer.#NativeCallbacks(System.Int32,System.IntPtr,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "ManagedSteam.Constants+GameServer")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "ManagedSteam.Constants+Matchmaking")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "ManagedSteam.Constants+Networking")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "ManagedSteam.ServicesGameServer+ExceptionDelegate")]
[assembly: SuppressMessage("Microsoft.Design", "CA1036:OverrideMethodsOnComparableTypes", Scope = "type", Target = "ManagedSteam.SteamTypes.ServerNetworkAddress")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.CloudGetFileNameAndSizeResult.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.CloudGetFileNameAndSizeResult.#sender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.CloudGetQuotaResult.#availableBytesSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.CloudGetQuotaResult.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.CloudGetQuotaResult.#totalBytesSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.CloudGetUGCDetailsResult.#appIDSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.CloudGetUGCDetailsResult.#creatorSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.CloudGetUGCDetailsResult.#fileSizeSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.CloudGetUGCDetailsResult.#nameSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.CloudGetUGCDetailsResult.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.CloudGetUGCDownloadProgressResult.#bytesDownloadedSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.CloudGetUGCDownloadProgressResult.#bytesExpectedSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.CloudGetUGCDownloadProgressResult.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.FriendsGetClanActivityCountsResult.#Chatting")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.FriendsGetClanActivityCountsResult.#InGame")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.FriendsGetClanActivityCountsResult.#Online")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.FriendsGetClanActivityCountsResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.FriendsGetClanChatMessageResult.#ChatEntryType")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.FriendsGetClanChatMessageResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.FriendsGetClanChatMessageResult.#Sender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.FriendsGetClanChatMessageResult.#Text")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.FriendsGetFriendGamePlayedResult.#FriendGameInfo")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.FriendsGetFriendGamePlayedResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.FriendsGetFriendMessageResult.#ChatEntryType")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.FriendsGetFriendMessageResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.FriendsGetFriendMessageResult.#Text")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.GameServerGetAuthSessionTicketResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.GameServerGetAuthSessionTicketResult.#TicketSize")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.GameServerGetNextOutgoingPacketResult.#NetAdr")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.GameServerGetNextOutgoingPacketResult.#Port")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.GameServerGetNextOutgoingPacketResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.GameServerGetUserAchievementResult.#Achieved")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.GameServerGetUserAchievementResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.GameServerSendUserConnectAndAuthenticateResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.GameServerSendUserConnectAndAuthenticateResult.#SteamIDUser")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.GameServerStatsGetUserStatFloatResult.#FloatValue")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.GameServerStatsGetUserStatFloatResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.GameServerStatsGetUserStatIntResult.#IntValue")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.GameServerStatsGetUserStatIntResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetFavoriteGameResult.#AppID")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetFavoriteGameResult.#ConnPort")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetFavoriteGameResult.#Flags")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetFavoriteGameResult.#IP")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetFavoriteGameResult.#Port")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetFavoriteGameResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetFavoriteGameResult.#Time32LastPlayedOnServer")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchmakingGetLobbyChatEntryResult.#ChatEntryType")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchmakingGetLobbyChatEntryResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchmakingGetLobbyChatEntryResult.#SteamIDUser")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetLobbyDataByIndexResult.#Key")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetLobbyDataByIndexResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetLobbyDataByIndexResult.#Value")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetLobbyGameServerResult.#GameServerIP")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetLobbyGameServerResult.#GameServerPort")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetLobbyGameServerResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.MatchMakingGetLobbyGameServerResult.#SteamIDGameServer")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingGetListenSocketInfoResult.#Ip")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingGetListenSocketInfoResult.#Port")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingGetListenSocketInfoResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingGetP2PSessionStateResult.#P2PSessionState")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingGetP2PSessionStateResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingGetSocketInfoResult.#IpRemote")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingGetSocketInfoResult.#PortRemote")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingGetSocketInfoResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingGetSocketInfoResult.#SocketStatus")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingGetSocketInfoResult.#SteamIDRemote")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingIsDataAvaibleOnSocketResult.#MsgSize")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingIsDataAvaibleOnSocketResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingIsDataAvailableResult.#MsgSize")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingIsDataAvailableResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingIsDataAvailableResult.#Socket")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingIsP2PPacketAvailableResult.#MsgSize")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingIsP2PPacketAvailableResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingReadP2PPacketResult.#MsgSize")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingReadP2PPacketResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingReadP2PPacketResult.#SteamIDRemote")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingRetrieveDataFromSocketResult.#MsgSize")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingRetrieveDataFromSocketResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingRetrieveDataResult.#MsgSize")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingRetrieveDataResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.NetworkingRetrieveDataResult.#Socket")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetAchievementAndUnlockTimeResult.#achievedSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetAchievementAndUnlockTimeResult.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetAchievementAndUnlockTimeResult.#unlockTimeSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetAchievementResult.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetAchievementResult.#sender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetAchievmentAchievedPercent.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetAchievmentAchievedPercent.#sender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetGlobalStat.#doubleSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetGlobalStat.#longSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetGlobalStat.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetGlobalStatHistory.#doubleSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetGlobalStatHistory.#longSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetGlobalStatHistory.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetMostAchievedAchievementInfo.#achievedSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetMostAchievedAchievementInfo.#nameSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetMostAchievedAchievementInfo.#percentSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetMostAchievedAchievementInfo.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetNextMostAchievedAchievementInfo.#achievedSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetNextMostAchievedAchievementInfo.#nameSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetNextMostAchievedAchievementInfo.#percentSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetNextMostAchievedAchievementInfo.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetStatFloatResult.#FloatValue")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetStatFloatResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetStatIntResult.#IntValue")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetStatIntResult.#Result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetUserAchievementAndUnlockTimeResult.#achievedSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetUserAchievementAndUnlockTimeResult.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetUserAchievementAndUnlockTimeResult.#unlockTimeSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetUserAchievementResult.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetUserAchievementResult.#sender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetUserStatResult.#floatDataSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetUserStatResult.#intDataSender")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "ManagedSteam.StatsGetUserStatResult.#result")]
[assembly: SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings", MessageId = "0#", Scope = "member", Target = "ManagedSteam.IFriends.#ActivateGameOverlayToWebPage(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1056:UriPropertiesShouldNotBeStrings", Scope = "member", Target = "ManagedSteam.CallbackStructures.CloudGetPublishedFileDetailsResult.#Url")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "ManagedSteam.Implementations.Friends.#DownloadClanActivityCounts(ManagedSteam.SteamTypes.SteamID[])")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "2", Scope = "member", Target = "ManagedSteam.Implementations.MatchmakingServers.#PingServer(System.UInt32,System.UInt16,ManagedSteam.MatchmakingPingResponse)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "2", Scope = "member", Target = "ManagedSteam.Implementations.MatchmakingServers.#PlayerDetails(System.UInt32,System.UInt16,ManagedSteam.MatchmakingPlayersResponse)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "ManagedSteam.Implementations.MatchmakingServers.#RequestLANServerList(ManagedSteam.SteamTypes.AppID,ManagedSteam.MatchmakingServerListResponse)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "2", Scope = "member", Target = "ManagedSteam.Implementations.MatchmakingServers.#ServerRules(System.UInt32,System.UInt16,ManagedSteam.MatchmakingRulesResponse)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "ManagedSteam.Implementations.Stats.#DownloadLeaderboardEntriesForUsers(ManagedSteam.SteamTypes.LeaderboardHandle,ManagedSteam.SteamTypes.SteamID[])")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "3", Scope = "member", Target = "ManagedSteam.Implementations.Stats.#GetDownloadedLeaderboardEntry(ManagedSteam.SteamTypes.LeaderboardEntriesHandle,System.Int32,ManagedSteam.SteamTypes.LeaderboardEntry&,System.Int32[])")]
[assembly: SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "3", Scope = "member", Target = "ManagedSteam.Implementations.Stats.#UploadLeaderboardScore(ManagedSteam.SteamTypes.LeaderboardHandle,ManagedSteam.SteamTypes.LeaderboardUploadScoreMethod,System.Int32,System.Int32[])")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "ElseWhere", Scope = "member", Target = "ManagedSteam.SteamTypes.AuthSessionResponse.#LoggedInElseWhere")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "MatchMaking", Scope = "type", Target = "ManagedSteam.MatchMakingGetFavoriteGameResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "MatchMaking", Scope = "type", Target = "ManagedSteam.MatchMakingGetLobbyDataByIndexResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "MatchMaking", Scope = "type", Target = "ManagedSteam.MatchMakingGetLobbyGameServerResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "MatchMaking", Scope = "type", Target = "ManagedSteam.SteamTypes.MatchMakingKeyValuePair")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "MatchMaking", Scope = "type", Target = "ManagedSteam.SteamTypes.MatchMakingServerResponse")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "MilliSeconds", Scope = "member", Target = "ManagedSteam.SteamTypes.LeaderboardDisplayType.#TimeMilliSeconds")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Achievment", Scope = "type", Target = "ManagedSteam.StatsGetAchievmentAchievedPercent")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Adr", Scope = "member", Target = "ManagedSteam.GameServerGetNextOutgoingPacketResult.#NetAdr")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Anticheat", Scope = "member", Target = "ManagedSteam.SteamTypes.DenyReason.#IncompatibleAnticheat")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Avaible", Scope = "type", Target = "ManagedSteam.NetworkingIsDataAvaibleOnSocketResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Avg", Scope = "member", Target = "ManagedSteam.IGameServerStats.#UpdateUserAvgRateStat(ManagedSteam.SteamTypes.SteamID,System.String,System.Single,System.Double)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Bot", Scope = "member", Target = "ManagedSteam.SteamTypes.GameServerItem.#BotPlayers")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Bot", Scope = "member", Target = "ManagedSteam.IGameServer.#SetBotPlayerCount(System.Int32)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Milli", Scope = "member", Target = "ManagedSteam.SteamTypes.LeaderboardDisplayType.#TimeMilliSeconds")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Num", Scope = "member", Target = "ManagedSteam.IMatchmaking.#GetNumLobbyMembers(ManagedSteam.SteamTypes.SteamID)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Steamworks")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Utils", Scope = "member", Target = "ManagedSteam.Steam.#Utils")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Utils", Scope = "type", Target = "ManagedSteam.IUtils")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "e", Scope = "type", Target = "ManagedSteam.ServicesGameServer+ExceptionDelegate")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.AchievementIcon.#op_Inequality(ManagedSteam.SteamTypes.AchievementIcon,ManagedSteam.SteamTypes.AchievementIcon)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.AchievementIcon.#op_Inequality(ManagedSteam.SteamTypes.AchievementIcon,ManagedSteam.SteamTypes.AchievementIcon)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.AchievementIcon.#op_Equality(ManagedSteam.SteamTypes.AchievementIcon,ManagedSteam.SteamTypes.AchievementIcon)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.AchievementIcon.#op_Equality(ManagedSteam.SteamTypes.AchievementIcon,ManagedSteam.SteamTypes.AchievementIcon)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.AppID.#op_Inequality(ManagedSteam.SteamTypes.AppID,ManagedSteam.SteamTypes.AppID)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.AppID.#op_Inequality(ManagedSteam.SteamTypes.AppID,ManagedSteam.SteamTypes.AppID)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.AppID.#op_Equality(ManagedSteam.SteamTypes.AppID,ManagedSteam.SteamTypes.AppID)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.AppID.#op_Equality(ManagedSteam.SteamTypes.AppID,ManagedSteam.SteamTypes.AppID)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.AuthTicketHandle.#op_Inequality(ManagedSteam.SteamTypes.AuthTicketHandle,ManagedSteam.SteamTypes.AuthTicketHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.AuthTicketHandle.#op_Inequality(ManagedSteam.SteamTypes.AuthTicketHandle,ManagedSteam.SteamTypes.AuthTicketHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.AuthTicketHandle.#op_Equality(ManagedSteam.SteamTypes.AuthTicketHandle,ManagedSteam.SteamTypes.AuthTicketHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.AuthTicketHandle.#op_Equality(ManagedSteam.SteamTypes.AuthTicketHandle,ManagedSteam.SteamTypes.AuthTicketHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.GameID.#op_Inequality(ManagedSteam.SteamTypes.GameID,ManagedSteam.SteamTypes.GameID)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.GameID.#op_Inequality(ManagedSteam.SteamTypes.GameID,ManagedSteam.SteamTypes.GameID)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.GameID.#op_Equality(ManagedSteam.SteamTypes.GameID,ManagedSteam.SteamTypes.GameID)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.GameID.#op_Equality(ManagedSteam.SteamTypes.GameID,ManagedSteam.SteamTypes.GameID)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "comsumer", Scope = "member", Target = "ManagedSteam.ICloud.#PublishVideo(ManagedSteam.SteamTypes.WorkshopVideoProviders,System.String,System.String,System.String,ManagedSteam.SteamTypes.AppID,System.String,System.String,ManagedSteam.SteamTypes.RemoteStoragePublishedFileVisibility,System.Collections.Generic.IList`1<System.String>)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.IconHandle.#op_Inequality(ManagedSteam.SteamTypes.IconHandle,ManagedSteam.SteamTypes.IconHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.IconHandle.#op_Inequality(ManagedSteam.SteamTypes.IconHandle,ManagedSteam.SteamTypes.IconHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.IconHandle.#op_Equality(ManagedSteam.SteamTypes.IconHandle,ManagedSteam.SteamTypes.IconHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.IconHandle.#op_Equality(ManagedSteam.SteamTypes.IconHandle,ManagedSteam.SteamTypes.IconHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Adr", Scope = "member", Target = "ManagedSteam.IGameServer.#GetNextOutgoingPacket(System.Byte[],System.UInt32&,System.UInt16&)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "bot", Scope = "member", Target = "ManagedSteam.IGameServer.#SetBotPlayerCount(System.Int32)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.ImageHandle.#op_Inequality(ManagedSteam.SteamTypes.ImageHandle,ManagedSteam.SteamTypes.ImageHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.ImageHandle.#op_Inequality(ManagedSteam.SteamTypes.ImageHandle,ManagedSteam.SteamTypes.ImageHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.ImageHandle.#op_Equality(ManagedSteam.SteamTypes.ImageHandle,ManagedSteam.SteamTypes.ImageHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.ImageHandle.#op_Equality(ManagedSteam.SteamTypes.ImageHandle,ManagedSteam.SteamTypes.ImageHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "dest", Scope = "member", Target = "ManagedSteam.INetworking.#ReadP2PPacket(System.Byte[],System.Int32)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "dest", Scope = "member", Target = "ManagedSteam.INetworking.#ReadP2PPacket(System.Byte[],System.UInt32&,ManagedSteam.SteamTypes.SteamID&,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "dest", Scope = "member", Target = "ManagedSteam.INetworking.#RetrieveData(ManagedSteam.SteamTypes.NetListenSocketHandle,System.Byte[])")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "dest", Scope = "member", Target = "ManagedSteam.INetworking.#RetrieveData(ManagedSteam.SteamTypes.NetListenSocketHandle,System.Byte[],System.UInt32&,ManagedSteam.SteamTypes.NetSocketHandle&)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "dest", Scope = "member", Target = "ManagedSteam.INetworking.#RetrieveDataFromSocket(ManagedSteam.SteamTypes.NetSocketHandle,System.Byte[])")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "dest", Scope = "member", Target = "ManagedSteam.INetworking.#RetrieveDataFromSocket(ManagedSteam.SteamTypes.NetSocketHandle,System.Byte[],System.UInt32&)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "p", Scope = "member", Target = "ManagedSteam.INetworking.#SendP2PPacket(ManagedSteam.SteamTypes.SteamID,System.Byte[],ManagedSteam.SteamTypes.P2PSend,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.LeaderboardEntriesHandle.#op_Inequality(ManagedSteam.SteamTypes.LeaderboardEntriesHandle,ManagedSteam.SteamTypes.LeaderboardEntriesHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.LeaderboardEntriesHandle.#op_Inequality(ManagedSteam.SteamTypes.LeaderboardEntriesHandle,ManagedSteam.SteamTypes.LeaderboardEntriesHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.LeaderboardEntriesHandle.#op_Equality(ManagedSteam.SteamTypes.LeaderboardEntriesHandle,ManagedSteam.SteamTypes.LeaderboardEntriesHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.LeaderboardEntriesHandle.#op_Equality(ManagedSteam.SteamTypes.LeaderboardEntriesHandle,ManagedSteam.SteamTypes.LeaderboardEntriesHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.LeaderboardHandle.#op_Inequality(ManagedSteam.SteamTypes.LeaderboardHandle,ManagedSteam.SteamTypes.LeaderboardHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.LeaderboardHandle.#op_Inequality(ManagedSteam.SteamTypes.LeaderboardHandle,ManagedSteam.SteamTypes.LeaderboardHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.LeaderboardHandle.#op_Equality(ManagedSteam.SteamTypes.LeaderboardHandle,ManagedSteam.SteamTypes.LeaderboardHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.LeaderboardHandle.#op_Equality(ManagedSteam.SteamTypes.LeaderboardHandle,ManagedSteam.SteamTypes.LeaderboardHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.NetListenSocketHandle.#op_Inequality(ManagedSteam.SteamTypes.NetListenSocketHandle,ManagedSteam.SteamTypes.NetListenSocketHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.NetListenSocketHandle.#op_Inequality(ManagedSteam.SteamTypes.NetListenSocketHandle,ManagedSteam.SteamTypes.NetListenSocketHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.NetListenSocketHandle.#op_Equality(ManagedSteam.SteamTypes.NetListenSocketHandle,ManagedSteam.SteamTypes.NetListenSocketHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.NetListenSocketHandle.#op_Equality(ManagedSteam.SteamTypes.NetListenSocketHandle,ManagedSteam.SteamTypes.NetListenSocketHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.NetSocketHandle.#op_Inequality(ManagedSteam.SteamTypes.NetSocketHandle,ManagedSteam.SteamTypes.NetSocketHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.NetSocketHandle.#op_Inequality(ManagedSteam.SteamTypes.NetSocketHandle,ManagedSteam.SteamTypes.NetSocketHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.NetSocketHandle.#op_Equality(ManagedSteam.SteamTypes.NetSocketHandle,ManagedSteam.SteamTypes.NetSocketHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.NetSocketHandle.#op_Equality(ManagedSteam.SteamTypes.NetSocketHandle,ManagedSteam.SteamTypes.NetSocketHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.PublishedFileId.#op_Inequality(ManagedSteam.SteamTypes.PublishedFileId,ManagedSteam.SteamTypes.PublishedFileId)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.PublishedFileId.#op_Inequality(ManagedSteam.SteamTypes.PublishedFileId,ManagedSteam.SteamTypes.PublishedFileId)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.PublishedFileId.#op_Equality(ManagedSteam.SteamTypes.PublishedFileId,ManagedSteam.SteamTypes.PublishedFileId)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.PublishedFileId.#op_Equality(ManagedSteam.SteamTypes.PublishedFileId,ManagedSteam.SteamTypes.PublishedFileId)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.PublishedFileUpdateHandle.#op_Inequality(ManagedSteam.SteamTypes.PublishedFileUpdateHandle,ManagedSteam.SteamTypes.PublishedFileUpdateHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.PublishedFileUpdateHandle.#op_Inequality(ManagedSteam.SteamTypes.PublishedFileUpdateHandle,ManagedSteam.SteamTypes.PublishedFileUpdateHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.PublishedFileUpdateHandle.#op_Equality(ManagedSteam.SteamTypes.PublishedFileUpdateHandle,ManagedSteam.SteamTypes.PublishedFileUpdateHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.PublishedFileUpdateHandle.#op_Equality(ManagedSteam.SteamTypes.PublishedFileUpdateHandle,ManagedSteam.SteamTypes.PublishedFileUpdateHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.ServerListRequestHandle.#op_Inequality(ManagedSteam.SteamTypes.ServerListRequestHandle,ManagedSteam.SteamTypes.ServerListRequestHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.ServerListRequestHandle.#op_Inequality(ManagedSteam.SteamTypes.ServerListRequestHandle,ManagedSteam.SteamTypes.ServerListRequestHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.ServerListRequestHandle.#op_Equality(ManagedSteam.SteamTypes.ServerListRequestHandle,ManagedSteam.SteamTypes.ServerListRequestHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.ServerListRequestHandle.#op_Equality(ManagedSteam.SteamTypes.ServerListRequestHandle,ManagedSteam.SteamTypes.ServerListRequestHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.ServerQueryHandle.#op_Inequality(ManagedSteam.SteamTypes.ServerQueryHandle,ManagedSteam.SteamTypes.ServerQueryHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.ServerQueryHandle.#op_Inequality(ManagedSteam.SteamTypes.ServerQueryHandle,ManagedSteam.SteamTypes.ServerQueryHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.ServerQueryHandle.#op_Equality(ManagedSteam.SteamTypes.ServerQueryHandle,ManagedSteam.SteamTypes.ServerQueryHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.ServerQueryHandle.#op_Equality(ManagedSteam.SteamTypes.ServerQueryHandle,ManagedSteam.SteamTypes.ServerQueryHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.SteamID.#op_Inequality(ManagedSteam.SteamTypes.SteamID,ManagedSteam.SteamTypes.SteamID)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.SteamID.#op_Inequality(ManagedSteam.SteamTypes.SteamID,ManagedSteam.SteamTypes.SteamID)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.SteamID.#op_Equality(ManagedSteam.SteamTypes.SteamID,ManagedSteam.SteamTypes.SteamID)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.SteamID.#op_Equality(ManagedSteam.SteamTypes.SteamID,ManagedSteam.SteamTypes.SteamID)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.UGCHandle.#op_Inequality(ManagedSteam.SteamTypes.UGCHandle,ManagedSteam.SteamTypes.UGCHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.UGCHandle.#op_Inequality(ManagedSteam.SteamTypes.UGCHandle,ManagedSteam.SteamTypes.UGCHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "x", Scope = "member", Target = "ManagedSteam.SteamTypes.UGCHandle.#op_Equality(ManagedSteam.SteamTypes.UGCHandle,ManagedSteam.SteamTypes.UGCHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "y", Scope = "member", Target = "ManagedSteam.SteamTypes.UGCHandle.#op_Equality(ManagedSteam.SteamTypes.UGCHandle,ManagedSteam.SteamTypes.UGCHandle)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#AvatarImageLoaded")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IUtils.#CheckFileSignature")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IMatchmaking.#FavoritesListChanged")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#FriendRichPresenceUpdate")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#GameConnectedChatJoin")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#GameConnectedChatLeave")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#GameConnectedClanChatMsg")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#GameConnectedFriendChatMsg")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#GameLobbyJoinRequested")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#GameRichPresenceJoinRequested")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#GameServerChangeRequested")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#GSClientAchievementStatus")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#GSClientApprove")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#GSClientDeny")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#GSClientGroupStatus")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#GSClientKick")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#GSGameplayStats")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#GSPolicyResponse")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServerStats.#GSStatsUnloaded")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IUtils.#IPCountry")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IMatchmaking.#LobbyChatMsg")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IMatchmaking.#LobbyChatUpdate")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IMatchmaking.#LobbyDataUpdate")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IMatchmaking.#LobbyGameCreated")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IMatchmaking.#LobbyInvite")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IMatchmaking.#LobbyKicked")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IUtils.#LowBatteryPower")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.INetworking.#P2PSessionConnectFail")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.INetworking.#P2PSessionRequest")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#PersonaStateChange")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.INetworking.#SocketStatusCallback")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IUtils.#SteamAPICallCompleted")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#SteamServerConnectFailure")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#SteamServersConnected")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#SteamServersDisconnected")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IUtils.#SteamShutdown")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#ValidateAuthTicketResponse")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#AssociateWithClanResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#ClanOfficerListResponseResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ICloud.#CloudUserVoteDetailsResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#ComputeNewPlayerCompatibilityResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#DownloadClanActivityCountsResultResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#FriendsEnumerateFollowingList")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#FriendsGetFollowerCount")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#FriendsIsFollowing")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServer.#GSReputation")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServerStats.#GSStatsReceived")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IGameServerStats.#GSStatsStored")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IFriends.#JoinClanChatRoomCompletionResultResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IMatchmaking.#LobbyCreatedResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IMatchmaking.#LobbyEnterResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.IMatchmaking.#LobbyMatchListResult")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "member", Target = "ManagedSteam.ServicesGameServer.#ExceptionThrown")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "ManagedSteam.ServicesGameServer+ExceptionDelegate")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope = "type", Target = "ManagedSteam.SteamTypes.ChatEntryType")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope = "type", Target = "ManagedSteam.SteamTypes.ChatMemberStateChange")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope = "type", Target = "ManagedSteam.SteamTypes.PersonaChange")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope = "type", Target = "ManagedSteam.SteamTypes.ServerMode")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1714:FlagsEnumsShouldHavePluralNames", Scope = "type", Target = "ManagedSteam.SteamTypes.UserRestriction")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1717:OnlyFlagsEnumsShouldHavePluralNames", Scope = "type", Target = "ManagedSteam.SteamTypes.WorkshopVideoProviders")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "float", Scope = "member", Target = "ManagedSteam.GameServerStatsGetUserStatFloatResult.#FloatValue")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "float", Scope = "member", Target = "ManagedSteam.StatsGetStatFloatResult.#FloatValue")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "int", Scope = "member", Target = "ManagedSteam.GameServerStatsGetUserStatIntResult.#IntValue")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "int", Scope = "member", Target = "ManagedSteam.StatsGetStatIntResult.#IntValue")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "int", Scope = "member", Target = "ManagedSteam.StatsGetUserStatResult.#intDataSender")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "long", Scope = "member", Target = "ManagedSteam.StatsGetGlobalStat.#longSender")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "string", Scope = "member", Target = "ManagedSteam.IFriends.#InviteUserToGame(ManagedSteam.SteamTypes.SteamID,System.String)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "string", Scope = "member", Target = "ManagedSteam.IGameServer.#InitGameServer(System.UInt32,System.UInt16,System.UInt16,System.UInt32,ManagedSteam.SteamTypes.AppID,System.String)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames", MessageId = "string", Scope = "member", Target = "ManagedSteam.ServicesGameServer.#Initialize(System.UInt32,System.UInt16,System.UInt16,System.UInt16,ManagedSteam.SteamTypes.ServerMode,System.String)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "flag", Scope = "member", Target = "ManagedSteam.IFriends.#ActivateGameOverlayToStore(ManagedSteam.SteamTypes.AppID,ManagedSteam.SteamTypes.OverlayToStoreFlag)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flags", Scope = "member", Target = "ManagedSteam.IFriends.#GetFriendByIndex(System.Int32,ManagedSteam.SteamTypes.FriendFlags)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flags", Scope = "member", Target = "ManagedSteam.IFriends.#GetFriendCount(ManagedSteam.SteamTypes.FriendFlags)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flags", Scope = "member", Target = "ManagedSteam.IFriends.#HasFriend(ManagedSteam.SteamTypes.SteamID,ManagedSteam.SteamTypes.FriendFlags)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "flags", Scope = "member", Target = "ManagedSteam.IGameServer.#InitGameServer(System.UInt32,System.UInt16,System.UInt16,System.UInt32,ManagedSteam.SteamTypes.AppID,System.String)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "flags", Scope = "member", Target = "ManagedSteam.IMatchmaking.#AddFavoriteGame(ManagedSteam.SteamTypes.AppID,System.UInt32,System.UInt16,System.UInt16,System.UInt32,System.UInt32)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "flags", Scope = "member", Target = "ManagedSteam.IMatchmaking.#GetFavoriteGame(System.Int32,ManagedSteam.SteamTypes.AppID&,System.UInt32&,System.UInt16&,System.UInt16&,System.UInt32&,System.UInt32&)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "flags", Scope = "member", Target = "ManagedSteam.IMatchmaking.#RemoveFavoriteGame(ManagedSteam.SteamTypes.AppID,System.UInt32,System.UInt16,System.UInt16,System.UInt32)")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Doesnt", Scope = "member", Target = "ManagedSteam.SteamTypes.ChatRoomEnterResponse.#DoesntExist")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Doesnt", Scope = "member", Target = "ManagedSteam.CallbackStructures.ComputeNewPlayerCompatibilityResult.#PlayersThatCandidateDoesntLike")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Dont", Scope = "member", Target = "ManagedSteam.CallbackStructures.ComputeNewPlayerCompatibilityResult.#ClanPlayersThatDontLikeCandidate")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Dont", Scope = "member", Target = "ManagedSteam.CallbackStructures.ComputeNewPlayerCompatibilityResult.#PlayersThatDontLikeCandidate")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flag", Scope = "member", Target = "ManagedSteam.Constants+Matchmaking.#FavoriteFlagFavorite")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flag", Scope = "member", Target = "ManagedSteam.Constants+Matchmaking.#FavoriteFlagHistory")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flag", Scope = "member", Target = "ManagedSteam.Constants+Matchmaking.#FavoriteFlagNone")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flag", Scope = "type", Target = "ManagedSteam.SteamTypes.OverlayToStoreFlag")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flags", Scope = "member", Target = "ManagedSteam.CallbackStructures.FavoritesListChanged.#Flags")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flags", Scope = "member", Target = "ManagedSteam.MatchMakingGetFavoriteGameResult.#Flags")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flags", Scope = "member", Target = "ManagedSteam.CallbackStructures.PersonaStateChange.#ChangeFlags")]
[assembly: SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flags", Scope = "type", Target = "ManagedSteam.SteamTypes.FriendFlags")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "connectionPort", Scope = "member", Target = "ManagedSteam.SteamTypes.ServerNetworkAddress.#Init(System.UInt32,System.UInt16,System.UInt16)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "ip", Scope = "member", Target = "ManagedSteam.SteamTypes.ServerNetworkAddress.#Init(System.UInt32,System.UInt16,System.UInt16)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "queryPort", Scope = "member", Target = "ManagedSteam.SteamTypes.ServerNetworkAddress.#Init(System.UInt32,System.UInt16,System.UInt16)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "value", Scope = "member", Target = "ManagedSteam.SteamTypes.MatchMakingKeyValuePair.#Key")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "value", Scope = "member", Target = "ManagedSteam.SteamTypes.MatchMakingKeyValuePair.#Value")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "ManagedSteam.Implementations.Friends.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "ManagedSteam.Implementations.GameServer.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.CallbackStructures.GSClientAchievementStatus.#Unlocked")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Utility.NativeBuffer.#ReadFromUnmanagedMemory()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Utility.NativeBuffer.#ToBytes(System.Int64[])")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Utility.NativeBuffer.#ToInt(System.Byte[])")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Utility.NativeString.#ToNativeAsAnsi()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.Utility.NativeString.#ToStringFromAnsi()")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "ManagedSteam.SteamTypes.ServerNetworkAddress.#Create(System.IntPtr,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ManagedSteam.Implementations.MatchmakingServers.#ServerRequest(ManagedSteam.Implementations.MatchmakingServers+ServerRequestType,ManagedSteam.SteamTypes.AppID,ManagedSteam.SteamTypes.MatchMakingKeyValuePair[],ManagedSteam.MatchmakingServerListResponse)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ManagedSteam.ServicesGameServer.#IsAvailable")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "ManagedSteam.Steam.#IsAvailable")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "ManagedSteam.Utility.NativeBuffer.#CopyToNative`1(!!0)")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope = "member", Target = "ManagedSteam.Utility.NativeString.#nativeAnsi")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope = "member", Target = "ManagedSteam.Utility.NativeString.#nativeUtf8")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope = "member", Target = "ManagedSteam.SteamTypes.SteamParamStringArray.#nativeDoubleStringArray")]
[assembly: SuppressMessage("Microsoft.Reliability", "CA2006:UseSafeHandleToEncapsulateNativeResources", Scope = "member", Target = "ManagedSteam.SteamTypes.SteamParamStringArray.#nativeStructMemory")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope = "member", Target = "ManagedSteam.Utility.NativeBuffer.#CopyToNative`1(!!0)")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope = "member", Target = "ManagedSteam.Utility.NativeBuffer.#.ctor(System.Int32)")]
[assembly: SuppressMessage("Microsoft.Security", "CA2122:DoNotIndirectlyExposeMethodsWithLinkDemands", Scope = "member", Target = "ManagedSteam.NativeHelpers.#ToStringAnsi(System.IntPtr)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "ManagedSteam.Implementations.MatchmakingServers.#ServerRequest(ManagedSteam.Implementations.MatchmakingServers+ServerRequestType,ManagedSteam.SteamTypes.AppID,ManagedSteam.SteamTypes.MatchMakingKeyValuePair[],ManagedSteam.MatchmakingServerListResponse)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "ManagedSteam.Utility.NativeBuffer.#FromBytes`1(System.Byte[],ManagedSteam.Utility.NativeBuffer+ConvertFromBytes`1<!!0>)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2217:DoNotMarkEnumsWithFlags", Scope = "type", Target = "ManagedSteam.SteamTypes.FriendFlags")]
[assembly: SuppressMessage("Microsoft.Design", "CA1008:EnumsShouldHaveZeroValue", Scope = "type", Target = "ManagedSteam.SteamTypes.ChatRoomEnterResponse")]
[assembly: SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible", Scope = "type", Target = "ManagedSteam.Constants+VersionInfo")]
[assembly: AssemblyTitle("ManagedSteam")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Ludosity AB")]
[assembly: AssemblyProduct("Steamworks for Unity")]
[assembly: AssemblyCopyright("Copyright © Ludosity AB 2011-2014")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: Guid("447fdbd5-1ece-421f-9c07-b2b3b116e086")]
[assembly: AssemblyFileVersion("1.8.128")]
